version: '3.8'

volumes:
  n8n_db_storage:
  n8n_storage:
  n8n_redis_storage:
  caddy_data:
  caddy_config:
  structify_db_storage:

networks:
  # Internal network for DB/Redis n8n communication
  n8n_internal_bridge:
    driver: bridge
  cv_react_internal_bridge:
    driver: bridge
  structify_bridge:
    driver: bridge
  # Reference the macvlan network created via CLI
  macvlan:
    external: true

x-shared: &shared
  restart: always
  image: docker.n8n.io/n8nio/n8n
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=n8n_postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=${N8N_POSTGRES_DB}
    - DB_POSTGRESDB_USER=${N8N_POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_PASSWORD}
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=n8n_redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - N8N_ENCRYPTION_KEY=Avenue4060
    - N8N_PROTOCOL=https
    - WEBHOOK_URL=https://n8n.damiankaplon.site/
  volumes:
    - n8n_storage:/home/node/.n8n
  networks:
    - n8n_internal_bridge
  depends_on:
    n8n_redis:
      condition: service_healthy
    n8n_postgres:
      condition: service_healthy

services:
  n8n_postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${N8N_POSTGRES_USER}
      - POSTGRES_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - POSTGRES_DB=${N8N_POSTGRES_DB}
    volumes:
      - n8n_db_storage:/var/lib/postgresql/data
    networks:
      - n8n_internal_bridge
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U poplar3080 -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n_redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - n8n_redis_storage:/data
    networks:
      - n8n_internal_bridge
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *shared
    networks:
      - n8n_internal_bridge

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./origin.pem:/etc/ssl/caddy/origin.pem
      - ./origin.key:/etc/ssl/caddy/origin.key
      - ./auth-app-origin.pem:/etc/ssl/caddy/auth-app-origin.pem
      - ./auth-app-origin.key:/etc/ssl/caddy/auth-app-origin.key
    networks:
      n8n_internal_bridge:
      cv_react_internal_bridge:
      structify_bridge:
      macvlan:
        ipv4_address: 192.168.0.230
    depends_on:
      - n8n
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel run
    networks:
      - n8n_internal_bridge

  cv-react:
    image: cv-react:latest
    container_name: cv-react
    restart: always
    networks:
      - cv_react_internal_bridge

  n8n-worker:
    <<: *shared
    command: worker

  structify_postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${STRUCTIFY_POSTGRES_DB}
      - POSTGRES_USER=${STRUCTIFY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${STRUCTIFY_POSTGRES_PASSWORD}
      - KC_DB_USER=${KC_DB_USER}
      - KC_DB_PASS=${KC_DB_PASS}
      - KC_DB_NAME=${KC_DB_NAME}
    volumes:
      - structify_db_storage:/var/lib/postgresql/data
      - ./structify/db:/docker-entrypoint-initdb.d
    networks:
      - structify_bridge

  structify_keycloak:
    image: kc:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://structify_postgres/keycloak
      KC_DB_USERNAME: ${STRUCTIFY_POSTGRES_USER}
      KC_DB_PASSWORD: ${STRUCTIFY_POSTGRES_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: ${STRUCTIFY_KC_HOSTNAME}
      KEYCLOAK_ADMIN: ${STRUCTIFY_KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${STRUCTIFY_KC_ADMIN_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/origin.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/origin.key
    command: start --optimized
    networks:
      - structify_bridge
    volumes:
      - ./origin.pem:/opt/keycloak/conf/origin.pem
      - ./origin.key:/opt/keycloak/conf/origin.key
    depends_on:
      - structify_postgres

